version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: osimis/orthanc
    build:
      context: .
      dockerfile: Dockerfile
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    volumes:
      - "/Users/theophilushomawoo/Documents/stage/galeo/python/OrthancGif:/python/:ro"
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
       ORTHANC__NAME: "orthanc"
       VERBOSE_ENABLED: "true"
       VERBOSE_STARTUP: "true"
       ORTHANC__PYTHON_VERBOSE: "true"
       PLUGIN__PYTHON_ENABLED: "true"
       ORTHANC__PYTHON_SCRIPT: "/python/plugin.py"
secrets:
  orthanc.json:
    file: orthanc.json
